#!/usr/bin/env python

import sys

import i18nize_templates


try:
    # 128+ is reserved by the shell
    sys.exit(min(i18nize_templates.main(sys.argv), 127))
except KeyboardInterrupt:
    sys.exit(1)
